### PR TITLE
fix:semantic-release replace plugin configuration

### PR DESCRIPTION
**Pull request by YurelyCamacho**
## Pull Request description
Fix semantic-release replace plugin configuration.
Solving issue #47 

## Pull Request checklists

This PR is a:
- [ ] bug-fix
- [ ] new feature
- [x ] maintenance

About this PR:
- [x ] it includes tests.
- [ ] the tests are executed on CI.
- [ ] the tests generate log file(s) (path).
- [ ] pre-commit hooks were executed locally.
- [ ] this PR requires a project documentation update.

Author's checklist:
- [ ] I have reviewed the changes and it contains no misspelling.
- [ ] The code is well commented, especially in the parts that contain more complexity.
- [x ] New and old tests passed locally.

## Reviewer's Checklist

- [ ] I managed to reproduce the problem locally from the `main` branch
- [x ] I managed to test the new changes locally
- [x ] I confirm that the issues mentioned were fixed/resolved .
```

### CODE REVIEW

**Review by xmnlab — CHANGES_REQUESTED** [review]
this one is really trick. I think you managed to fix half of the problem.

first you would need to add `  # semantic-release` here -> https://github.com/osl-incubator/cookiecutter-python/blob/main/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.package_slug%7D%7D/__init__.py#L14

but it would not be totally complete because you will need to add to .releaserc.json a variable to define what kind of quote it is using and replace it in the from/to line:


for examle:



```

{%- if cookiecutter.auto_format_tool == 'blue' %}
  {%- set QUOTE = "'" -%}
{%- elif cookiecutter.auto_format_tool == 'black' %}
  {%- set QUOTE = '"' -%}
{%- else %}
  {%- set QUOTE = "'" -%}
{%- endif %}
```

and 

```
            "from": "__version__ = {{ QUOTE }}.*{{ QUOTE }}  # semantic-release",
            "to": "__version__ = {{ QUOTE }}${nextRelease.version}{{ QUOTE }}  # semantic-release",
```
Something like this .. but please check if everything is correct.

thanks for working on that.

**Comment by YurelyCamacho** [comment]
@xmnlab Thank you. One question: the variable in the .releaserc.json must be between the first {} or outside them?

**Comment by xmnlab** [comment]
> @xmnlab Thank you. One question: the variable in the .releaserc.json must be between the first {} or outside them?

I am not following you here .. could you give more details about your question please?

**Comment by xmnlab** [comment]
> `{ "branches": ["main"], "tagFormat": "${version}", "plugins": [...` This is how the file starts. What you told me about adding the variable `QUOTE` is done before that { , i.e. in the first line?

yep .. add it as the first lines of the file

**Review by xmnlab — APPROVED** [review]
LGTM! @YurelyCamacho thanks for working on that!

**Pull request merged**
